- hosts: test_ansible 
  sudo: yes
  gather_facts: no
  become_user: anser
  become: True
  connection: ssh

  tasks:
  - name: "Print Date"
    shell: date
    register: date_output

  - debug: var=date_output
